function Roll(max) {
  return Math.floor((Math.random() * max) + 1);
}

function ArrayRandom(arr) {
    return arr[Roll(arr.length) - 1];
}

function guidGenerator() {
    var S4 = function() {
       return (((1+Math.random())*0x10000)|0).toString(16).substring(1);
    };
    return (S4()+S4()+"-"+S4()+"-"+S4()+"-"+S4()+"-"+S4()+S4()+S4());
}

function textWindow(title, content) {
    let guid = guidGenerator();
    new Dialog({
        title: title,
        content: `<input id="${guid}" value="${content}" readonly> <script>document.getElementById("${guid}").select(); document.execCommand('copy'); window.getSelection().removeAllRanges(); </script>`,
        buttons: {}
    }).render(true, {width: 200});
}

const HALFLING_MALE = [
"Ulrich Grassdew",
"Flyneon Whisperbrace",
"Rimo Softbrush",
"Rihace Springglide",
"Finvias Fastflower",
"Neorin Swiftlade",
"Zalpos Mildearth",
"Sanlan Cherryeye",
"Zalpher Hillace",
"Xolos Amberheart",
"Barlos Whisperwater",
"Garhace Goldmeadow",
"Kaspos Commongather",
"Meramin Fastfoot",
"Pimnad Twilightcrest",
"Lasire Hogdance",
"Larin Warmkettle",
"Baryver Thistlebrush",
"Gofer Brushbottle",
"Faleon Embertop",
"Mardak Longgrove",
"Irabin Embermouse",
"Tarwrick Stoutwoods",
"Belver Fernhand",
"Faltran Eartheye",
"Sanret Dustsurge",
"Joumo Greeneyes",
"Gorich Silentdew",
"Lasire Summerspirit",
"Flynder Glenfinger",
"Goos Ravencreek",
"Tehace Talldance",
"Valnan Deepspark",
"Zalwan Silentwoods",
"Yarorin Leafbrush",
"Kortran Earthbranch",
"Arhace Teaseeker",
"Falfire Foremouse",
"Garyver Freelade",
"Wenver Cloudcheeks",
"Xanumo Grassbough",
"Tarpher Heartcobble",
"Cororin Tenfeet",
"Teyver Freestep",
"Riczu Laughingstride",
"Urizu Clearblossom",
"Riclos Ravenbloom",
"Quozin Fatmouse",
"Flynace Proudsun",
"Garder Leafmane"
]

const HALFLING_FEMALE = [
"Zefsica Stoutmeadow",
"Therlile Grandwood",
"Belhaly Mossspark",
"Xida Elderbeam",
"Trynlile Mildwater",
"Erarana Brightgather",
"Theryra Cherrydance",
"Welgwen Lonespell",
"Fenna Proudkettle",
"Idaleigh Littlemantle",
"Uviwyn Stillhands",
"Gramita Littlesky",
"Malgrace Deepbrand",
"Uvialyn Shadowtop",
"Qubrix Lightbarrel",
"Xiwyse Clearglide",
"Wisira Keenace",
"Hakath Summerfingers",
"Uviula Lonebluff",
"Diawyn Amberbranch",
"Trynwyn Emberbarrel",
"Fenbyn Bramblebranch",
"Hilalyn Keenman",
"Marvyre Leacheeks",
"Yessys Cinderbottle",
"Lebyn Hilllade",
"Weleni Rivergrove",
"Elilyse Marblecreek",
"Pruda Grassrabbit",
"Uvisys Hogfeet",
"Veryola Warmfellow",
"Salile Flintbranch",
"Gracaryn Glowmane",
"Odiphina Swiftearth",
"Maltina Mossvale",
"Fayda Applebrand",
"Jilwyse Bronzelade",
"Calmia Fatstride",
"Jilleigh Shadowwoods",
"Shaenys Commongather",
"Zenlie Mildstep",
"Pruda Fatbrand",
"Xiri Strongman",
"Xizana Wildtop",
"Eoeni Goldfeet",
"Rimia Elderbridge",
"Elitrix Brushmane",
"Isada Glensun",
"Isala Fogdew",
"Xanni Glowdream"
]

const TIEFLING_MALE = [
"Garros",
"Ebxius",
"Eklius",
"Thexes",
"Kyshoon",
"Lokeakos",
"Arkadius",
"Salvenom",
"Ebemon",
"Malreus",
"Valnon",
"Zherxes",
"Salmos",
"Kaimong",
"Iacis",
"Rerias",
"Koscis",
"Themenos",
"Kaiil",
"Thyakos",
"Skacis",
"Arreus",
"Akthos",
"Shachar",
"Nephthos",
"Maldos",
"Rolmos",
"Malethor",
"Urimus",
"Zherxire",
"Skaron",
"Koszer",
"Carris",
"Zorus",
"Kamong",
"Karus",
"Kyxus",
"Malmeros",
"Kaxes",
"Ebmenos",
"Barcius",
"Valmus",
"Morlius",
"Aetil",
"Barzer",
"Aetxius",
"Thynevir",
"Karon",
"Urxius",
"Aetmus"
]

const TIEFLING_FEMALE = [
"Zaifaris",
"Crefirith",
"Sarvari",
"Vallith",
"Eapione",
"Hisborys",
"Brilypsis",
"Valki",
"Aramine",
"Shabis",
"Dasolis",
"Dorsolis",
"Lilrissa",
"Afspira",
"Initari",
"Rovine",
"Lillith",
"Qusolis",
"Yurissa",
"Marmaia",
"Nethdoris",
"Aravari",
"Zaimeia",
"Nepunith",
"Nithsolis",
"Maseis",
"Iniyis",
"Aninarei",
"Griki",
"Levari",
"Seiritish",
"Valnarei",
"Zaphi",
"Dalies",
"Mithmeia",
"Yalypsis",
"Marnarei",
"Histish",
"Pesvari",
"Levlista",
"Marnirith",
"Ealypsis",
"Nexibis",
"Daloth",
"Dimtari",
"Aniphi",
"Dorki",
"Agnekaria",
"Brilaia",
"Nethbis"
]

const HUMAN_MALE = [
"Reibeim Dhahlu",
"Kheihnud Biner",
"Stokvid Blazeslayer",
"Nevum Monsterbane",
"Fosin Ketsk",
"Ven Darnav",
"Valdam Wiselight",
"Eth Embershaper",
"Kihkato Rindranzift",
"Bah-zik ralahd",
"Dosdadjat Notvatvube",
"Tondoor Navzalbu",
"Tobrules Vumabre",
"Zitan Zesoldur",
"Urem Shima",
"Esun Rheiham",
"Nordadd Whitsurge",
"Rugril Spiritwood",
"Kargem Buz",
"Fan Kevritsk",
"Stronneth Pyreshot",
"Or Alpenmourn",
"Hitheoza Jandacrot",
"Kozir Mivim",
"Jinzesdesk Rontildyeka",
"Vlendec Vovremu",
"Shup Hiaoy",
"Rinchaimiez Resqala",
"Grordor Zelbornen",
"Jezeir Khassar",
"Mukhen Khimem",
"Mellalm Crowbinder",
"Tengom Shieldscream",
"Grergor Notsk",
"Gor Vinodz",
"Zuldorth Tarrenflower",
"Frem Flintwhisper",
"Geon-vijo bildrekdald",
"Hirheoh Laltrak",
"Borvomod Yelburkadi",
"Felvisk Zuryami",
"Sunienraiz Jebreval",
"Mintor Hilirnul",
"Morkan Threeoak",
"Troth Dayhand",
"Judecho Vivuhreft",
"Rinesdic Tredzediku",
"Jervoot Mabega",
"Mearcean Uldadre",
"Nehlum Rhassur",
"Brel Namiv"
]

const HUMAN_FEMALE = [
"Ruromah Bhuhad",
"Ozel Shesso",
"Larurru Marbleorb",
"Tezne Foreshade",
"Ralrelri Pinehide",
"Bivro Hawkhelm",
"Sufepho Zacrivruhd",
"Kizhe Zinkrikt",
"Fiveris Huthovitho",
"Yudha Tradamzi",
"Lientd Suzadra",
"Letd Jibrelor",
"Catopal Sheihrir",
"Kusranoll Windblight",
"Tusvai Burningkeep",
"Kana Butsk",
"Olostro Runestalker",
"Vilri Distantvigor",
"Kusathus Nekruprohr",
"Zirseldri Zildugavya",
"Fefri Merigu",
"Anc Juldonzon",
"Fiert Rulorge",
"Foshehroh Jane",
"Zohreih Huhla",
"Selzarvi Lonesoar",
"Rirli Hellmark",
"Zetha Reg",
"Ca Kadredz",
"Levefli Eaglewhisk",
"Kono Winterfire",
"Zofosha Nuekruuhkuhr",
"Tishi Zinskald",
"Yirsilmish Dunyaduba",
"Tenre Chibuki",
"Dalmf Virgistal",
"Eiml Hozarin",
"Cenosmuh Cokhu",
"Nihmal Hodim",
"Lolzaldru Alpenbreeze",
"Toldrih Flinttrapper",
"Waflatho Wyvernshield",
"Zene Forestroot",
"Cuzenos Razruezihd",
"Chohi Soldrufk",
"Nilmemvish Zanungonzi",
"Meldran Tibega",
"Eld Sadrelde",
"Olmd Senzildel",
"Nehlohlol Rhuhri",
"Carih Mened",
"Suchusvuh Horsewater",
"Ilzal Freetrack",
"Cesholro Eventoe",
"Cestra Pinesprinter",
"Nashafi Felruuhpuhr",
"Hazru Raltrahk",
"Larrafu Elzudolda",
"Ruchu Hatrelma",
"Lem Ildalis",
"Mancm Oldoven"
]

const DRAGONBORN_MALE = [
"Thexor Rasvull",
"Veaphinkojeal Lumivull",
"Gardikeash Nesqiroth",
"Kimphecaak Trouqull",
"Vuulrosh Sulwunax",
"Niaceath Wuturim",
"Klinxith Vraklasar",
"Alxishkmumel Shavull",
"Myithteranded Zorxan",
"Lilthud Vyuwarum",
"Yapashteler Ravocrath",
"Nyiathtuuth Caerbarum",
"Dambith Hedaar",
"Kialthaajen Pavarax",
"Shempanthok Nadaar",
"Caphinkan Rhociar",
"Kupiruush Nafras",
"Estixiardic Krivbroth",
"Tocid Dravroth",
"Clamphak Helasar",
"Alxul Udoziros",
"Funxash Drafras",
"Vilthendrardal Saxan",
"Vencinthid Worqull",
"Ilxuth Dralasar",
"Tirdil Jinhazar",
"Kraarrhakmear Durrakas",
"Liankeashkmac Drabor",
"Thirthar Kildhall",
"Prelkeranash Zrarinn",
"Therthishkmamoth Kilskan",
"Nilkekmeroth Calubarum",
"Vuumpathaner Natrin",
"Myearen Durnaar",
"Drethtash Jarwunax",
"Myombath Orlakris",
"Meraalirron Beljurn",
"Myiccikmerith Zorvarax",
"Exosh Vyulin",
"Alxad Ghevull",
"Nyericmaac Ravomash",
"Clembalomuath Krivcrath",
"Priccaarad Lorhadur",
"Myearrhucirgian Balghull",
"Clumten Jartrin",
"Tompinkundial Hiturim",
"Vunxaaneth Ravoskan",
"Nyalthas Frodorim",
"Nyulmec Tozavur",
"Thealthakergid Arzavur"
]

const DRAGONBORN_FEMALE = [
"Gaaldrixuurgar Arithibra",
"Klerthas Malqwen",
"Dupac Grixiris",
"Thephiantherrir Yrvayla",
"Gachuunthaamon Wrawyn",
"Shilran Oriyassa",
"Nyelthicun Rairith",
"Viphesec Fenfyire",
"Vacil Ophicys",
"Shiarthunshturec Thabith",
"Nyaathted Erlivys",
"Limpecmesh Dadalynn",
"Uumterin Bixora",
"Demtocnas Kelsira",
"Myankeanshtek Ahime",
"Yonxuundic Thernorae",
"Ustish Yrqorel",
"Clapuucarduus Phimeila",
"Apaac Sudrith",
"Iccastak Ushiyassa",
"Tuammikmaandis Phizys",
"Geracish Vyrathibra",
"Kilthethimuar Arixiris",
"Kuardocirdath Quilqorel",
"Linkudaac Irlymyse",
"Thancus Malliann",
"Drealrinthiallik Eshdrith",
"Krecucnargath Lilowyn",
"Therthandrash Zenfyire",
"Umpial Neskaryn",
"Myombocmac Hinrish",
"Klencunedel Qibirith",
"Pruxiniarrer Gridalynn",
"Primpinkamel Xythibra",
"Therasuun Valgissa",
"Eacar Gurdrith",
"Praachad Lorarith",
"Nyixath Lilogil",
"Nyastethis Oribis",
"Cirrhanshtinal Gurxiris",
"Craarrher Fenthibra",
"Nuarjenthunith Belwyn",
"Ankud Grizita",
"Krolkenthel Irienys",
"Prornuatirguad Afyire",
"Alxeric Crisvyre",
"Vurdoshtas Belshann",
"Lurdad Hameila",
"Gealmuth Xisgil",
"Cildritajul Cristhyra"
]

const HALFORC_MALE = [
"Kurabak",
"Okurall",
"Ukratur",
"Urthamarsh",
"Mugobur",
"Kelimar",
"Kamimar",
"Gretar",
"Mararak",
"Kilaruk",
"Ogguedak",
"Urtharall",
"Maloburk",
"Zavotar",
"Tanutar",
"Kalozur",
"Horagark",
"Therotur",
"Kilan",
"Renebak",
"Therudall",
"Gogark",
"Ukagar",
"Cogak",
"Renarimm",
"Zarazur",
"Aggadark",
"Oguidall",
"Okadak",
"Sararim",
"Gorurall",
"Budash",
"Barabak",
"Galabar",
"Kamidurk",
"Kalanars",
"Zoradim",
"Arnezur",
"Thurugall",
"Thuromur",
"Kurabash",
"Beluz",
"Kilebar",
"Gnaedar",
"Ukonar",
"Mukirsh",
"Goribark",
"Thaglar",
"Barotar",
"Makamash"
]

const HALFORC_FEMALE = [
"Nerook",
"Semadar",
"Sumati",
"Garezara",
"Zunagh",
"Sanez",
"Zoneki",
"Tuada",
"Laganar",
"Rawamar",
"Kinur",
"Rogur",
"Gryenir",
"Laguz",
"Tamigar",
"Alotur",
"Vanigu",
"Lagogu",
"Zanuri",
"Gryame",
"Rahkaz",
"Gine",
"Tuuti",
"Sinune",
"Rawozura",
"Semiri",
"Hurotir",
"Kotuzi",
"Mani",
"Puyunir",
"Temani",
"Fulatir",
"Kiritur",
"Shayuzur",
"Rashuwar",
"Gijogume",
"Gajadar",
"Keradar",
"Shayad",
"Kotune",
"Goridur",
"Zenerel",
"Gajiner",
"Puyetur",
"Aligri",
"Arid",
"Elash",
"Samener",
"Gajadur",
"Laganir"
]

const HALFELF_MALE = [
"Yorwarith",
"Barros",
"Sardeyr",
"Frilovar",
"Wilorin",
"Nilcoril",
"Davneak",
"Gaerdithas",
"Petvalor",
"Davcoril",
"Kriwarith",
"Corphanis",
"Eircoril",
"Yenparin",
"Lorneak",
"Vantorin",
"Gaermorn",
"Corminar",
"Gaerparin",
"Iloelor",
"Xanavor",
"Oriparin",
"Eirqarim",
"Yordithas",
"Iloben",
"Iandeyr",
"Walsariph",
"Dorfyr",
"Iloreak",
"Horenas",
"Davparin",
"Trafaelor",
"Rafvoril",
"Vanneak",
"Osvalor",
"Uanenas",
"Jamlamir",
"Gaerneiros",
"Walril",
"Wilxian",
"Vanword",
"Vanhomin",
"Lorvalor",
"Halfaelor",
"Tralanann",
"Marcraes",
"Belphanis",
"Uanlamir",
"Halparin",
"Meiovar"
]

const HALFELF_FEMALE = [
"Phayehana",
"Phayeyra",
"Dellynn",
"Quewalyn",
"Darphira",
"Jenfine",
"Relnys",
"Darnoa",
"Loracharis",
"Jilwalyn",
"Alustine",
"Alybwynn",
"Elienyphe",
"Vylqwyn",
"Quediane",
"Quetheris",
"Noryra",
"Venhana",
"Winhophe",
"Caryra",
"Saeldove",
"Elitheris",
"Galrora",
"Vengalyn",
"Aluona",
"Carnalore",
"Tylvyre",
"Faewalyn",
"Krikilia",
"Cozenya",
"Norxaris",
"Safmae",
"Olfine",
"Saftihne",
"Yllwaris",
"Saelcharis",
"Brenqarin",
"Wolyaries",
"Cogalyn",
"Tylnys",
"Arkaen",
"Delzenya",
"Tylqwyn",
"Winxaris",
"Tyldove",
"Quedove",
"Leselor",
"Therkilia",
"Phayefine",
"Ophinys"
]

const ELF_MALE = [
"Waesmaer Silverlight",
"Herquinal Mosswalker",
"Zumyarus Stillgleam",
"Daesalor Sunguard",
"Genric Greenvale",
"Fardithas Medronesh",
"Sylyarus Seminthraea",
"Traneiros Hathrisesh",
"Aeran Huresh",
"Iliwarin Flarniith",
"Yinlar Aspenlight",
"Iliydark Willowdream",
"Petzumin Emberlight",
"Beinorin Springheel",
"Aefir Shadowkind",
"Leonorin Sivi",
"Glynren Hiardiscihal",
"Traceran Culphe",
"Farlar Yievis",
"Norpeiros Ciphana",
"Aejor Aspencloud",
"Yinzumin Diamondspark",
"Daeven Cedarsinger",
"Dorsalor Featherfall",
"Valar Birchcloud",
"Aeqen Sheyshothrosh",
"Virfaren Dreystre",
"Fenzeiros Elthondronn",
"Morwarin Cimindrirrath",
"Kealar Deyldier",
"Qinlen Sagesinger",
"Uriberos Silentshadow",
"Ilipetor Gembrook",
"Elazeiros Starfond",
"Carkian Swiftspirit",
"Pettoris Ixiltiso",
"Aehorn Quecenariir",
"Wranwraek Ivo",
"Aejor Tiphidrannes",
"Zinhice Feidrinna",
"Dorneiros Emberflight",
"Leomaris Silverbeam",
"Carqen Hazelseeker",
"Zinberos Windbeam",
"Wranmyar Winterwalker",
"Farsalor Irnal",
"Genric Thelle",
"Sarsandoral Bustrevieth",
"Yinsalor Shusherethrith",
"Vawarin Kaldanno"
]

const ELF_FEMALE = [
"Ulahana Elderguard",
"Qihana Willowspark",
"Holavaris Firdream",
"Cairel Lunardream",
"Holagwyn Spiritsmile",
"Neriyra Sheltia",
"Wysara Drannish",
"Ravarie Yevascihant",
"Presmys Callaea",
"Faeroris Xeltirra",
"Phina Diamondwish",
"Xyrsys Stonestar",
"Holasatra Summergazer",
"Sharel Winterwish",
"Presra Aspenshadow",
"Caibella Thadrennoma",
"Zylthana Udrephel",
"Krisfina Walel",
"Olazorwyn Tunno",
"Joxisys Rassiphissos",
"Venthana Greenflow",
"Chaena Greensinger",
"Jomys Poplargazer",
"Holalynn Sunshine",
"Caisatra Oceanwatcher",
"Daecaryn Flalornelke",
"Olacyne Thidriremi",
"Vencaryn Flaphith",
"Iarthyra Vuphascesi",
"Presna Durnothran",
"Adxina Flowervale",
"Mialeth Fogseeker",
"Xilyra Willowfate",
"Liarona Eagerbreath",
"Ravadove Elderbirth",
"Ravazorwyn Shonnistiith",
"Cairona Liemedrennii",
"Helewenys Laldrothrin",
"Zinlana Hustris",
"Valfiel Cothi",
"Adnala Featherkind",
"Reyfina Lunarsmile",
"Xyrynore Boldgrove",
"Wysabella Bronzemind",
"Faebanise Alderfond",
"Chaebanise Laelice",
"Kriscyne Eyrisash",
"Wysana Tenestanniish",
"Iarbella Ciliho",
"Quiwenys Eshaea"
]

const GNOME_MALE = [
"Nini Starkbelch",
"Dorkur Gobblehide",
"Vallen Tinkertop",
"Sahim Cobbleligt",
"Uriben Twinriver",
"Horcorin Gegglereggle",
"Niner Elkadera",
"Panahik Gonggereten",
"Uriben Simplederis",
"Zillin Dambleremble",
"Umpip Thunderdrop",
"Trazu Silverflight",
"Jorkur Quillbell",
"Dorbis Swiftmask",
"Grapos Starkblock",
"Xalpip Homberanan",
"Urifan Sebbledobble",
"Kelkur Peplemiple",
"Tanrick Zernanoda",
"Briryn Belkutina",
"Sarug Deeppatch",
"Saldon Thundercollar",
"Dorkas Quicktrick",
"Albis Stoutdust",
"Yezu Fappletwist",
"Davwin Tapplenepple",
"Felrick Unnedase",
"Quaziver Ragglan",
"Yeser Lemplezemple",
"Sinwor Nusgranober",
"Bilkas Bafflebottom",
"Sinrick Singlefern",
"Panaxif Puddlemane",
"Corros Kindspring",
"Saldri Swiftspell",
"Merhik Dimmadosel",
"Kasbar Dorkedonel",
"Ipaybar Norcede",
"Valcryn Orgaroseck",
"Kelziver Paddleriddle",
"Yemin Twinkind",
"Lojin Quickcraft",
"Quamop Quillfern",
"Zancryn Strongcollar",
"Lokur Puddleflow",
"Dorlen Peglefegle",
"Davver Tulwobenemp",
"Erfiz Talkoner",
"Wrenan Larnibig",
"Merybar Aenpubarar"
]

const GNOME_FEMALE = [
"Uridysa Quietshield",
"Lorina Singletrick",
"Krila Bellowligt",
"Spidysa Goldcollar",
"Helza Fapplebranch",
"Daphimila Talkiders",
"Celmyn Heplegiple",
"Inanoa Resgras",
"Arisany Tinbeben",
"Triroe Zurnemp",
"Hellin Stouthand",
"Uferhana Shadowhand",
"Primyn Silverhold",
"Triyaris Whistlecase",
"Jelna Flukediggles",
"Taqaryn Halboll",
"Tifadysa Dengall",
"Tifayore Lirgeso",
"Nisys Ummlotoben",
"Eiliza Burresitel",
"Xarhana Tosslecollar",
"Mymiphi Stoutdust",
"Ylomila Boonsong",
"Tamila Broadcase",
"Spixi Finefern",
"Zinkasys Ribblezobble",
"Daphigani Nommlorobors",
"Welmila Hekkirobell",
"Kloyore Bopplemepple",
"Daphili Hunggatidomp",
"Dogani Starktop",
"Heswyse Palespark",
"Banssa Kindhide",
"Zanina Bafflestone",
"Orwyse Darkcloak",
"Loridira Aebbleni",
"Domila Meblelable",
"Helyaris Tercitan",
"Grenroe Remblewomble",
"Yofyx Dirnabiner",
"Priniana Ironback",
"Aripine Fappleshield",
"Banxi Wobbleriver",
"Carbi Fiddlehold",
"Caryaris Squigglelob",
"Nyhani Bogglegeggle",
"Orzyre Gemblewemble",
"Loriyore Pomporetemp",
"Nysany Feglefegle",
"Doci Ponpedan"
]

const DWARF_MALE = [
"Urmmek Frozenstone",
"Berron Stormbleeder",
"Dardrom Darkstrike",
"Gulgran Keenforce",
"Tharbrek Bravebraid",
"Gralren Bollert",
"Emkam Faldurk",
"Kromdohr Glazzom",
"Rannus Foduvam",
"Darkohm Grarthenn",
"Berdram Bronzekin",
"Gulrak Stonebreath",
"Gralnyl Thunderstrike",
"Huldain Smugforge",
"Kromkuhm Frostmane",
"Gralrigg Straefdoln",
"Brumgrom Grorthirerr",
"Thaldrom Grutguguln",
"Baermund Grulbrart",
"Thurdur Straellohok",
"Bhelmin Boldhorn",
"Gardain Moltenbane",
"Bhaldrom Bloodmantle",
"Emiggs Frozenstand",
"Malthran Truefound",
"Galthrum Strohan",
"Thuldur Tuhahr",
"Baernur Carthinirt",
"Bhelryl Hullehk",
"Gerkuhm Dronkek",
"Bromtharn Bravefist",
"Baerkahm Broadfeast",
"Grilnus Bigbelch",
"Banryl Gianthead",
"Baerdus Bravefinder",
"Gerdrom Mudihr",
"Melmor Strartherug",
"Thomiir Drebrarr",
"Gremdrak Drurthuk",
"Gimnir Molden",
"Daermur Mightbranch",
"Kramdur Flintfall",
"Hurmund Bigbelt",
"Fardain Marblestorm",
"Grandrum Kindreach",
"Kharmiir Latgark",
"Kharthrum Remnik",
"Melkuhm Cudarark",
"Bhalkam Lollek",
"Bhalthran Monkirr"
]

const DWARF_FEMALE = [
"Lesryn Lasthold",
"Nyssora Evensong",
"Lesslen Everpass",
"Kathtin Stoutblood",
"Raenryl Brightflight",
"Jinryl Talbrivohr",
"Karmyl Brotguvuk",
"Myrnys Brenkehr",
"Tazglian Mungohaln",
"Tornip Bangurahk",
"Naslyl Silveraxe",
"Belma Burrowguard",
"Mysva Hammerfront",
"Arnyss Goldheart",
"Dearthiel Firekind",
"Lassglia Gaemnanok",
"Mysva Mabrokurk",
"Brylledryn Botguhk",
"Brilthiel Cahenak",
"Lyesris Strorunahk",
"Nassnar Fireshaper",
"Elnas Hammertankard",
"Anmura Coldkin",
"Tisvian Evenmantle",
"Maevglia Stoutsong",
"Jennera Gruthgag",
"Belris Gruzzuhek",
"Rynros Drullihk",
"Brylmera Gladonehk",
"Reynlynn Coronn",
"Ednis Sternbreaker",
"Nassnora Truefall",
"Brulbera Boldgrace",
"Arnis Broadfront",
"Branbera Goldkin",
"Nasswin Luzzohen",
"Rundora Cordivirt",
"Daerla Glolbrogek",
"Einniss Graheck",
"Belnora Thruthgik",
"Bretlyn Lightbrow",
"Ranma Ironbranch",
"Raennia Frostdelver",
"Ingros Goldenbleeder",
"Karniss Brightaxe",
"Einvia Mereck",
"Tazdryn Mahegem",
"Rednis Straldann",
"Nisthiel Raelbrehig",
"Lesri Harekeck"
]

let dialogEditor = new Dialog({
  title: `Name Generator`,
  buttons: {
    human_male: {
      label: `Human Male`,
      callback: () => {
          textWindow("Human male name", ArrayRandom(HUMAN_MALE));
      }
    },
    human_female: {
      label: `Human Female`,
      callback: () => {
          textWindow("Human female name", ArrayRandom(HUMAN_FEMALE));
      }
    },
    halfling_male: {
      label: `Halfling Male`,
      callback: () => {
          textWindow("Halfling male name", ArrayRandom(HALFLING_MALE));
      }
    },
    halfling_female: {
      label: `Halfling Female`,
      callback: () => {
          textWindow("Halfling female name", ArrayRandom(HALFLING_FEMALE));
      }
    },
    tiefling_male: {
      label: `Tiefling Male`,
      callback: () => {
          textWindow("Tiefling male name", ArrayRandom(TIEFLING_MALE));
      }
    },
    tiefling_female: {
      label: `Tiefling Female`,
      callback: () => {
          textWindow("Tiefling female name", ArrayRandom(TIEFLING_FEMALE));
      }
    },
    dragonborn_male: {
      label: `Dragonborn Male`,
      callback: () => {
          textWindow("Dragonborn male name", ArrayRandom(DRAGONBORN_MALE));
      }
    },
    dragonborn_female: {
      label: `Dragonborn Female`,
      callback: () => {
          textWindow("Dragonborn female name", ArrayRandom(DRAGONBORN_FEMALE));
      }
    },
    elf_male: {
      label: `Elf Male`,
      callback: () => {
          textWindow("Elf male name", ArrayRandom(ELF_MALE));
      }
    },
    elf_female: {
      label: `Elf Female`,
      callback: () => {
          textWindow("Elf female name", ArrayRandom(ELF_FEMALE));
      }
    },
    halfelf_male: {
      label: `Halfelf Male`,
      callback: () => {
          textWindow("Half-elf male name", ArrayRandom(HALFELF_MALE));
      }
    },
    halfelf_female: {
      label: `Halfelf Female`,
      callback: () => {
          textWindow("Half-elf female name", ArrayRandom(HALFELF_FEMALE));
      }
    },
    halforc_male: {
      label: `Halforc Male`,
      callback: () => {
          textWindow("Half-orc male name", ArrayRandom(HALFORC_MALE));
      }
    },
    halforc_female: {
      label: `Halforc Female`,
      callback: () => {
          textWindow("Half-orc female name", ArrayRandom(HALFORC_FEMALE));
      }
    },
    gnome_male: {
      label: `Gnome Male`,
      callback: () => {
          textWindow("Gnome male name", ArrayRandom(GNOME_MALE));
      }
    },
    gnome_female: {
      label: `Gnome Female`,
      callback: () => {
          textWindow("Gnome female name", ArrayRandom(GNOME_FEMALE));
      }
    },
    dwarf_male: {
      label: `Dwarf Male`,
      callback: () => {
          textWindow("Dwarf male name", ArrayRandom(DWARF_MALE));
      }
    },
    dwarf_female: {
      label: `Dwarf Female`,
      callback: () => {
          textWindow("Dwarf female name", ArrayRandom(DWARF_FEMALE));
      }
    },
    close: {
      label: `==Exit==`
    },
  },
  default: "close",
  close: () => {}
});
await dialogEditor.render(true, {width: 650});